project:
  type: website
  preview:
    port: 4200
  resources:
    - posts/notebook_best_practices.html
    - posts/notebook-best-practices.html
    # Can't remember what next line was for
    # - "*.png"

website:
  open-graph: true
  twitter-card:
    creator: "@wasimlorgat"
    site: "@wasimlorgat"
  title: "Wasim Lorgat"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - text: Posts
        file: index.qmd
      - projects.qmd
      - tils/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/wasimlorgat
      - icon: github
        href: https://github.com/seem
      - icon: linkedin
        href: https://linkedin.com/in/wasim-lorgat
      - icon: rss
        text: Posts
        href: index.xml
      - icon: rss
        text: TILs
        href: tils/index.xml

  site-url: https://wasimlorgat.com
  repo-url: https://github.com/seem/blog
  repo-actions: [edit, source, issue]

format:
  html:
    theme: seem.scss
    highlight-style: seem.theme
    include-in-header: [analytics-head.html]
    include-after-body: [analytics-body.html]
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      # Enable banner style title blocks
      title-block-banner: false
      author: Wasim Lorgat
      # Can't yet enable this because it causes "On this page" to appear on index.html
      # even if I set its post-level `toc: false`
      # toc: true
      title-block-categories: false
      toc-depth: 5

comments:
  giscus: 
    repo: seem/blog
    repo-id: R_kgDOIBWk3A
    category: Announcements
    category-id: DIC_kwDOIBWk3M4CSSa6
    mapping: pathname
    loading: lazy
    input-position: top
